# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
a = np.random.random((2,3,5))
print(a)

[[[0.64974792 0.1510422  0.56939855 0.69705539 0.68942234]
  [0.86059646 0.83882008 0.99250074 0.65707707 0.98763244]
  [0.20868767 0.78416399 0.15136683 0.06117068 0.26654301]]

 [[0.25913579 0.38810313 0.59495834 0.20655643 0.88126353]
  [0.42033836 0.90005624 0.23679955 0.67913105 0.31924496]
  [0.23557998 0.79728785 0.55625979 0.23133996 0.71452751]]]


In [12]:

y = np.random.randint(100 , size=(2, 3,  5))

print(y)

[[[66  4 47 53 35]
  [97 42  4 83 55]
  [ 4  2 75 30 89]]

 [[22 52 98 37 54]
  [88 95 65 10  0]
  [50 63 58  0 72]]]


In [ ]:
# Method 3

#### 4. Print *a*.


In [8]:
a

array([[[0.64974792, 0.1510422 , 0.56939855, 0.69705539, 0.68942234],
        [0.86059646, 0.83882008, 0.99250074, 0.65707707, 0.98763244],
        [0.20868767, 0.78416399, 0.15136683, 0.06117068, 0.26654301]],

       [[0.25913579, 0.38810313, 0.59495834, 0.20655643, 0.88126353],
        [0.42033836, 0.90005624, 0.23679955, 0.67913105, 0.31924496],
        [0.23557998, 0.79728785, 0.55625979, 0.23133996, 0.71452751]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [53]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [54]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [43]:
y = a+b
#you can see the error: not the same shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 8. Are you able to add *a* and *b*? Why or why not?


In [45]:
z = np.concatenate((a, b))
# We are not able to add because it's not the same matrix size

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 5 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [60]:
c = b.transpose(1,2,0 )   #specify the ax number (0,1,2) = where 5*2*3 -> 0=5 ; 1=2 and 2 = 3
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [59]:
d = a + c
d
#because they have the same matrix size

array([[[1.64974792, 1.1510422 , 1.56939855, 1.69705539, 1.68942234],
        [1.86059646, 1.83882008, 1.99250074, 1.65707707, 1.98763244],
        [1.20868767, 1.78416399, 1.15136683, 1.06117068, 1.26654301]],

       [[1.25913579, 1.38810313, 1.59495834, 1.20655643, 1.88126353],
        [1.42033836, 1.90005624, 1.23679955, 1.67913105, 1.31924496],
        [1.23557998, 1.79728785, 1.55625979, 1.23133996, 1.71452751]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [61]:
a

array([[[0.64974792, 0.1510422 , 0.56939855, 0.69705539, 0.68942234],
        [0.86059646, 0.83882008, 0.99250074, 0.65707707, 0.98763244],
        [0.20868767, 0.78416399, 0.15136683, 0.06117068, 0.26654301]],

       [[0.25913579, 0.38810313, 0.59495834, 0.20655643, 0.88126353],
        [0.42033836, 0.90005624, 0.23679955, 0.67913105, 0.31924496],
        [0.23557998, 0.79728785, 0.55625979, 0.23133996, 0.71452751]]])

The difference between a and d are the values and it's exactly a+1 = d because we were summing 1 to each value of the matrix a.

In [62]:
d

array([[[1.64974792, 1.1510422 , 1.56939855, 1.69705539, 1.68942234],
        [1.86059646, 1.83882008, 1.99250074, 1.65707707, 1.98763244],
        [1.20868767, 1.78416399, 1.15136683, 1.06117068, 1.26654301]],

       [[1.25913579, 1.38810313, 1.59495834, 1.20655643, 1.88126353],
        [1.42033836, 1.90005624, 1.23679955, 1.67913105, 1.31924496],
        [1.23557998, 1.79728785, 1.55625979, 1.23133996, 1.71452751]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [63]:
e = a*c

In [65]:
e

array([[[0.64974792, 0.1510422 , 0.56939855, 0.69705539, 0.68942234],
        [0.86059646, 0.83882008, 0.99250074, 0.65707707, 0.98763244],
        [0.20868767, 0.78416399, 0.15136683, 0.06117068, 0.26654301]],

       [[0.25913579, 0.38810313, 0.59495834, 0.20655643, 0.88126353],
        [0.42033836, 0.90005624, 0.23679955, 0.67913105, 0.31924496],
        [0.23557998, 0.79728785, 0.55625979, 0.23133996, 0.71452751]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [68]:
np.array_equal(a, e, equal_nan=False)
# They're equal because we multiply a * c and c is a matrix of value 1.

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [79]:
d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)


1.992500739182864
1.061170679843089
1.5328602620279306


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [89]:
f = np.empty((2,3,5))
f

array([[[1.64974792, 1.1510422 , 1.56939855, 1.69705539, 1.68942234],
        [1.86059646, 1.83882008, 1.99250074, 1.65707707, 1.98763244],
        [1.20868767, 1.78416399, 1.15136683, 1.06117068, 1.26654301]],

       [[1.25913579, 1.38810313, 1.59495834, 1.20655643, 1.88126353],
        [1.42033836, 1.90005624, 1.23679955, 1.67913105, 1.31924496],
        [1.23557998, 1.79728785, 1.55625979, 1.23133996, 1.71452751]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [94]:
for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0,0])):
            if d[i,j,k] == d_min:
                f[i,j,k] = 0
            if d[i,j,k] == d_max:
                f[i,j,k] = 100
            if d[i,j,k] == d_mean:
                f[i,j,k] = 50
            if d[i,j,k] < d_mean:
                f[i,j,k] = 25
            if d[i,j,k] > d_mean:
                f[i,j,k] = 75

print(f)






[[[75. 25. 75. 75. 75.]
  [75. 75. 75. 75. 75.]
  [25. 75. 25. 25. 25.]]

 [[25. 25. 75. 25. 75.]
  [25. 75. 25. 75. 25.]
  [25. 75. 75. 25. 75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [96]:
print(d)
print(f)

[[[1.64974792 1.1510422  1.56939855 1.69705539 1.68942234]
  [1.86059646 1.83882008 1.99250074 1.65707707 1.98763244]
  [1.20868767 1.78416399 1.15136683 1.06117068 1.26654301]]

 [[1.25913579 1.38810313 1.59495834 1.20655643 1.88126353]
  [1.42033836 1.90005624 1.23679955 1.67913105 1.31924496]
  [1.23557998 1.79728785 1.55625979 1.23133996 1.71452751]]]
[[[75. 25. 75. 75. 75.]
  [75. 75. 75. 75. 75.]
  [25. 75. 25. 25. 25.]]

 [[25. 25. 75. 25. 75.]
  [25. 75. 25. 75. 25.]
  [25. 75. 75. 25. 75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here